name: Prueba secrets self-hosted

on:
  push:
    branches: [ '**' ]

jobs:
  comparar-tokens:
    runs-on: self-hosted
    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: Bash
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if [ "$DEV_TOKEN" = "$LOCAL_DEV_TOKEN" ]; then
            echo 'OK - Los tokens COINCIDEN'
          else
            echo 'FAIL - Los tokens NO coinciden'
            exit 1
          fi
